version: '3.8'

services:
  sudoku-validator:
    image: python:3.13
    working_dir: /app
    volumes:
      - .:/app
    command: python cli.py
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    depends_on: []
    tty: true
    stdin_open: true