services:
  sudoku-validator:
    image: python:3.13
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "pip install -r requirements.txt && pytest"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true